// Code generated by the multiversx-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    shipment
    (
        init => init
        upgrade => upgrade
        getConfig => config
        create_shipment => create_shipment
        getConfigHash => get_config_hash
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
