// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    service
    (
        init => init
        getDefaultPrice => default_price
        getForwarderDefaultFee => forwarder_default_fee
        setCarrierAddress => set_carrier_address
        registerForwarder => register_forwarder
        unregisterForwarder => unregister_forwarder
        validate => validate
        quote => quote
        routeKey => route_key
        getRegisteredForwarders => get_registered_forwarders
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
